// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Group } from "./Group";
import type { Slot } from "./Slot";

export type Class = { seq: string, teacher: string | null, language: string | null, allowed: string | null, denied: string | null, info: string | null, note: string | null, slots: Array<Slot>, groups: Array<Group>, };
