// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Class } from "./Class";
import type { Dependency } from "./Dependency";

export type Course = { era: string, code: string, name: string, credits: string, category: string, nature: string | null, department: string, dependencies: Array<Array<Dependency>> | null, classes: Array<Class>, id: string, };
