// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GradeResponse } from "./GradeResponse";
import type { YearGpa } from "./YearGpa";

export type GradesResponse = { gpa: number, ranking: string, years: Array<YearGpa>, grades: Array<GradeResponse>, };
