// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GradeResponse = { code: string, name: string, score: string, grade: string, semester: string, nature: string | null, category: string, credits: number, department: string, ranking: string | null, students: string, };
