// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Slot } from "./Slot";

export type Group = { id: string, seq: string, teacher: string | null, undergraduate_number: string, graduate_number: string, male_number: string, female_number: string, undergraduate_capacity: string | null, graduate_capacity: string | null, seats: string | null, slots: Array<Slot>, };
