// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Slot } from "./Slot";

export type ScheduleResponse = { class: string, group: string | null, code: string, name: string, credits: string, category: string, nature: string | null, department: string, teacher: string | null, slots: Array<Slot>, language: string | null, info: string | null, id: string, undergraduate_number: string, graduate_number: string, male_number: string, female_number: string, undergraduate_capacity: string, graduate_capacity: string, grade_type: string, coin: string | null, };
