// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Slot = { day: number, room: string, weeks: Array<number>, period: [number, number], };
