// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserInfoResponse = { level: string, grade: string, department: string, major: string, };
