// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeasonGpa } from "./SeasonGpa";

export type YearGpa = { year: string, year_gpa: number, seasons: Array<SeasonGpa>, };
